### ISSUE TITLE
Any plans to work on recognition?

### ISSUE THREAD

**Issue by gutenye** [backrunner/paddleocr-onnx#1]
Hey, this is a great project. Is there a plan to work on the recognition part? Thanks.

**Comment by backrunner** [comment]
The reason that the recognition part has not been implemented yet is there's a strange issue in the detection part, the rects in the result are drifted compare to the original Python version.
I can't figure that out in that time, I think it's a great time to review it again and see if there's any available solution for it.
If this strange issue can be solved, I'll implement the recognition part ASAP.

**Comment by gutenye** [comment]
Closed as I've created a new package with detection and recognition on my own, that works on Node, Web, and React Native. I will open-source it soon. @backrunner can I re-use your `getBoxRects` code?
